# site properties and page defaults
title: AKR Superfamily
description: 

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default

#theme
remote_theme: pages-themes/slate@v0.2.0

#plugins
plugins:
- jekyll-remote-theme 

